# coding: utf-8

# flake8: noqa
"""
    REST-API_basic

    # Overview   This document specifies the MAP REST-API (OII) - **O**pen **I**ntrusion **I**nterface (**OII**).  The REST-API (former known as **O**pen **I**ntrusion **I**nterface [**OII**]), is implemented on the MAP system. This document is fully valid to the MAP panel firmware Version: <br> <br> **MAP_Update.1.4.0272.tar.bz2**<br>  To be backward compatible, all \"/get\", \"/post\" and other commands which includes \"OII\", will be still \"OII\".  New implemented features will be named as \"REST-API\" instead of \"OII\".  Please note that the following rules have been ignored when checking the OpenAPI documentation file against errors and warnings:   - [no-identical-paths](https://redocly.com/docs/cli/rules/no-identical-paths/)   - [no-ambiguous-paths](https://redocly.com/docs/cli/rules/no-ambiguous-paths/)   - [spec](https://redocly.com/docs/cli/rules/spec/)  The OpenAPI file is structured in the following groups: 1. REST-API_basic 2. REST-API_MUM  ## 1: REST-API_basic  All URLs described under this group contain all functions of released MAP panel firmware version 1.4.0176 All REST-API (OII) functions are also described in the following previous documents (PDF):     - ApplicationNotes.pdf   - BaseSpecification.pdf   - ResourceModel.pdf  This previous REST-API (OII) documentation can be downloaded [here](https://media.boschsecurity.com/fs/media/pb/media/extranet/map_partners/2019_oii_openintrusioninterface.zip). <br>   New features: - *Memory Info & statistics*     This feature is available from the MAP panel firmware version *<1.4.0xxx ToDo, replace*   - *NTP*  This feature is available from the MAP panel firmware version *<1.4.0xxx ToDo, replace*  - *supportfiles*     This feature is available from the MAP panel firmware version 1.4.0231  ## 2: REST-API_MUM  All URLs described in this group contain the features, which are added by the firmware version 1.4.0245   New Features: - *VDS2252 permissions*    Updated internal permissions with both mayClearMainPowerFailure and mayClearATS   ## HTTPS server certificates The MAP system is using so named \"unique self signed server certificates\" for HTTPS. The certificate files are created during the MAP panel start, if not already existing. Due to missing entropy and hardware resources, 2048-bit certificates are created. The MAP system guarantees those certificates will not change uncontrolled during lifetime. This guarantee is fullfilled by automated test during development.  ## General client requests   The MAP systems are **strongly limited** in hardware and software resources. This is why there are **limitations** using the MAP REST-API which **must** be considered to avoid erroneous behavior and a poor user experience.<br> - Use a ping to check the network availability **before** sending HTTP requests to the MAP panel. - The MAP panel can handle parallel requests. However, it is strongly recommended that a single client makes only serial requests.  - Parallel processing of many multiple requests will typically fail with negative response codes and overload the system. - Multiple requests to the same MAP panel must be serialized with a delay of at least 1 second between the last response and the next request. - The MAP panel might return the response codes 500 or a 503 or other response codes in case of overload. - Requests with HTTP Content-Length higher than 30000 bytes are not supported, HTTP Error Code 411 will be raised. - Receiving negative response codes caused by overload require a 60 seconds communication delay. - If the MAP panel does not (anymore) response at all, a delay of at least 5 minutes must be considered. - It is strongly recommended to use a connection pool for better HTTPS performance as well as lower CPU load on the MAP panel. - If the connection is cancelled or runs into timeout it is undefined whether the request will still be processed or not.  - After connection errors, the HTTPS connection must be closed and it is necessary again to check network availability by ping. - Cyclic request, e.g. ping, getting synchronization states and performing a time synchronization are allowed. - Cyclic request must not be more frequent than every 5 minutes. - Enabled **User Passcode Tamper** feature will prevent potential bruteforce attack. Retry count and lockout time is configurable via RPS for MAP. During the lockout any request will return code 401 for attacking IP. - In case of negative response codes, the client side should provide request and response logging to a file, with milliseconds timestamps, to support further analyses. - In case of interface errors or unexpected behaviour, the client side must provide request and response logging to a file, with milliseconds timestamps, e.g. activated by a client side debug level. - The MAP panel itself logs all database modifications, per default, to the history.log, what is strongly limited in number of entries and content. - The MAP panel itself does not log all HTTPS request and responses because of file system limitations. - TCP keepalive is enabled, lost connections will be dropped after 25 seconds.   ## HTTPS server limitations  Due to limited resources, MAP system generally does not process HTTPS requests simultaneously.  However, there are exceptions that are processed simultaneously: - **/syncstatus** - **/panel** - **/sub** - **/sub/\\*** - **/history**  All other URLs are executed sequentially.  Requests are queued and executed once execution units are available.  Simultaneous execution is limited to 3 simultaneous requests, processing time will be slower for multiple simultaneous requests.  Overloading REST-API can make MAP less responsive, in case of overload, the REST-API will generally respond with HTTP code 503, or, in case of heavy overload, will immediately close TCP socket without any response.    ## Response time guarantees  The following URLs have a guaranteed time, only if one HTTPS client connection at the same time.  The following URLs are guaranteed to execute their requests within 120 seconds: - **/history** - **/supportfile** - **/points** - **/couplers** - **/lsnauxs**  The following URLs are guaranteed to execute their requests within 60 seconds: - **/network** - **/syncstatus** - **/usermodellist** - **/outputs** - **/user** - **/mains** - **/groundfaults**  All other REST-API requests are guaranteed to be executed within 10 seconds.  ## License  Following URLs are only accessible with a valid MUM software license and only with a MAP-COM panel: - usermodel - usermodel/* - usermodellist - daymodel - daymodel/* - daymodellist - timemodel - timemodel/* - timemodellist - specialdaymodel - specialdaymodel/* - specialdaymodellist - smartkeymodel - smartkeymodel/* - smartkeymodellist - areaandtimemodel - areaandtimemodel/* - areaandtimemodellist - accessmodel - accessmodel/* - accessmodellist - permissionmodel - permissionmodel/* - permissionmodellist - mumusergroup - sharedkey - statistics - statistics/oii - statistics/db  Missing license will lead to HTTP 403 plain-text response, for example \"License missing MUM/usermodel\"  ## Security  Supported cipher suites:  **TLS1.3** (**recommended**) - TLS_AES_256_GCM_SHA384 - TLS_CHACHA20_POLY1305_SHA256 - TLS_AES_128_GCM_SHA256  **TLS1.2** - ECDHE-RSA-AES128-SHA256 - ECDHE-RSA-AES128-GCM-SHA256 - ECDHE-RSA-AES256-SHA384 - ECDHE-RSA-AES256-GCM-SHA384 - DHE-RSA-AES128-SHA256 - DHE-RSA-AES128-GCM-SHA256 - DHE-RSA-AES256-SHA256 - DHE-RSA-AES256-GCM-SHA384 - DHE-RSA-AES128-SHA  **TLS1.0** (**deprecated**! Not recommended to be used, has to be manually enabled in MAP panel configuration via RPS for MAP) - AES128-SHA - AES256-SHA

    The version of the OpenAPI document: 1.4.0272, 18.09.2024
    Contact: intrusion.emea@de.bosch.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from bosch-alarm-map.models.access_model import AccessModel
from bosch-alarm-map.models.access_model_id import AccessModelID
from bosch-alarm-map.models.access_model_list import AccessModelList
from bosch-alarm-map.models.access_model_list_all_of_list_inner import AccessModelListAllOfListInner
from bosch-alarm-map.models.access_model_sync_id import AccessModelSyncID
from bosch-alarm-map.models.access_modelist_post import AccessModelistPost
from bosch-alarm-map.models.area import Area
from bosch-alarm-map.models.area_and_time_model import AreaAndTimeModel
from bosch-alarm-map.models.area_and_time_model_id import AreaAndTimeModelID
from bosch-alarm-map.models.area_and_time_model_list import AreaAndTimeModelList
from bosch-alarm-map.models.area_and_time_model_list_all_of_list_inner import AreaAndTimeModelListAllOfListInner
from bosch-alarm-map.models.area_and_time_model_sync_id import AreaAndTimeModelSyncID
from bosch-alarm-map.models.area_and_time_modellist_post import AreaAndTimeModellistPost
from bosch-alarm-map.models.area_arm import AreaArm
from bosch-alarm-map.models.area_configuration import AreaConfiguration
from bosch-alarm-map.models.area_disarm import AreaDisarm
from bosch-alarm-map.models.area_list import AreaList
from bosch-alarm-map.models.area_post_responses import AreaPostResponses
from bosch-alarm-map.models.area_walktest_started import AreaWalktestStarted
from bosch-alarm-map.models.arming_info import ArmingInfo
from bosch-alarm-map.models.arming_info_why_not_ready_to_arm import ArmingInfoWhyNotReadyToArm
from bosch-alarm-map.models.arming_info_why_not_ready_to_disarm import ArmingInfoWhyNotReadyToDisarm
from bosch-alarm-map.models.arming_info_why_not_ready_to_force_arm import ArmingInfoWhyNotReadyToForceArm
from bosch-alarm-map.models.battery import Battery
from bosch-alarm-map.models.battery_list import BatteryList
from bosch-alarm-map.models.batterycharger import Batterycharger
from bosch-alarm-map.models.batterycharger_list import BatterychargerList
from bosch-alarm-map.models.bell_test_start import BellTestStart
from bosch-alarm-map.models.blocklock import Blocklock
from bosch-alarm-map.models.blocklock_list import BlocklockList
from bosch-alarm-map.models.chime_mode_start_stop import ChimeModeStartStop
from bosch-alarm-map.models.command import Command
from bosch-alarm-map.models.communicator import Communicator
from bosch-alarm-map.models.config import Config
from bosch-alarm-map.models.coupler import Coupler
from bosch-alarm-map.models.coupler_list import CouplerList
from bosch-alarm-map.models.create_sub import CreateSub
from bosch-alarm-map.models.created_sub import CreatedSub
from bosch-alarm-map.models.de_module import DEModule
from bosch-alarm-map.models.day_model import DayModel
from bosch-alarm-map.models.day_model_id import DayModelID
from bosch-alarm-map.models.day_model_list import DayModelList
from bosch-alarm-map.models.day_model_list_all_of_list_inner import DayModelListAllOfListInner
from bosch-alarm-map.models.day_model_sync_id import DayModelSyncID
from bosch-alarm-map.models.day_modellist_post import DayModellistPost
from bosch-alarm-map.models.desc import Desc
from bosch-alarm-map.models.desc_main_resources_inner import DescMainResourcesInner
from bosch-alarm-map.models.device import Device
from bosch-alarm-map.models.device_activate_deactivate import DeviceActivateDeactivate
from bosch-alarm-map.models.device_bypass_unbypass import DeviceBypassUnbypass
from bosch-alarm-map.models.device_configuration import DeviceConfiguration
from bosch-alarm-map.models.device_enable_disable import DeviceEnableDisable
from bosch-alarm-map.models.device_fw_version import DeviceFwVersion
from bosch-alarm-map.models.device_on_off import DeviceOnOff
from bosch-alarm-map.models.device_op_state import DeviceOpState
from bosch-alarm-map.models.device_update import DeviceUpdate
from bosch-alarm-map.models.device_walktest import DeviceWalktest
from bosch-alarm-map.models.devicefirmware_version import DevicefirmwareVersion
from bosch-alarm-map.models.devices_list import DevicesList
from bosch-alarm-map.models.diagnose import Diagnose
from bosch-alarm-map.models.diagnose_response import DiagnoseResponse
from bosch-alarm-map.models.error400 import Error400
from bosch-alarm-map.models.error409 import Error409
from bosch-alarm-map.models.evt import Evt
from bosch-alarm-map.models.evts import Evts
from bosch-alarm-map.models.fetch_events import FetchEvents
from bosch-alarm-map.models.fetched_events import FetchedEvents
from bosch-alarm-map.models.fire_detector import FireDetector
from bosch-alarm-map.models.fire_detector_list import FireDetectorList
from bosch-alarm-map.models.fire_detector_tested_sensors_inner import FireDetectorTestedSensorsInner
from bosch-alarm-map.models.get_accessmodel200_response import GetAccessmodel200Response
from bosch-alarm-map.models.get_areaandtimemodel200_response import GetAreaandtimemodel200Response
from bosch-alarm-map.models.get_daymodel200_response import GetDaymodel200Response
from bosch-alarm-map.models.get_permissionmodel200_response import GetPermissionmodel200Response
from bosch-alarm-map.models.get_smartkeymodel200_response import GetSmartkeymodel200Response
from bosch-alarm-map.models.get_specialdaymodel200_response import GetSpecialdaymodel200Response
from bosch-alarm-map.models.get_supervised_conns_siid200_response import GetSupervisedConnsSIID200Response
from bosch-alarm-map.models.get_timemodel200_response import GetTimemodel200Response
from bosch-alarm-map.models.get_usermodel_by_id200_response import GetUsermodelById200Response
from bosch-alarm-map.models.getarming_info import GetarmingInfo
from bosch-alarm-map.models.groundfault import Groundfault
from bosch-alarm-map.models.groundfault_list import GroundfaultList
from bosch-alarm-map.models.handling_state import HandlingState
from bosch-alarm-map.models.history import History
from bosch-alarm-map.models.inc import Inc
from bosch-alarm-map.models.inc_list import IncList
from bosch-alarm-map.models.incident_resource import IncidentResource
from bosch-alarm-map.models.infrastructure import Infrastructure
from bosch-alarm-map.models.infrastructure_device import InfrastructureDevice
from bosch-alarm-map.models.infrastructure_device_generic_property import InfrastructureDeviceGenericProperty
from bosch-alarm-map.models.infrastructure_device_properties import InfrastructureDeviceProperties
from bosch-alarm-map.models.infrastructure_device_rps_property import InfrastructureDeviceRPSProperty
from bosch-alarm-map.models.infrastructure_device_si_type import InfrastructureDeviceSIType
from bosch-alarm-map.models.internal_program import InternalProgram
from bosch-alarm-map.models.internal_program_ip_arming_info import InternalProgramIpArmingInfo
from bosch-alarm-map.models.internal_program_list import InternalProgramList
from bosch-alarm-map.models.internal_programs_configuration import InternalProgramsConfiguration
from bosch-alarm-map.models.ip_arming_info import IpArmingInfo
from bosch-alarm-map.models.keypad import Keypad
from bosch-alarm-map.models.keypad_list import KeypadList
from bosch-alarm-map.models.keyswitch import Keyswitch
from bosch-alarm-map.models.keyswitchlist import Keyswitchlist
from bosch-alarm-map.models.lsn_antimask_sensitivity_detection_range_property import LSNAntimaskSensitivityDetectionRangeProperty
from bosch-alarm-map.models.lsn_antimask_sensitivity_property import LSNAntimaskSensitivityProperty
from bosch-alarm-map.models.lsn_detector_sensitivity_property import LSNDetectorSensitivityProperty
from bosch-alarm-map.models.lsnemk36_configuration import LSNEMK36Configuration
from bosch-alarm-map.models.lsnemk36_configuration_any_of import LSNEMK36ConfigurationAnyOf
from bosch-alarm-map.models.lsnemk36_s_configuration import LSNEMK36SConfiguration
from bosch-alarm-map.models.lsngwaux_configuration import LSNGWAUXConfiguration
from bosch-alarm-map.models.lsngw_configuration import LSNGWConfiguration
from bosch-alarm-map.models.lsngw_configuration_create_post import LSNGWConfigurationCreatePost
from bosch-alarm-map.models.lsngw_configuration_delete_post import LSNGWConfigurationDeletePost
from bosch-alarm-map.models.lsngw_loop_configuration import LSNGWLoopConfiguration
from bosch-alarm-map.models.lsngw_loop_configuration_devices_inner import LSNGWLoopConfigurationDevicesInner
from bosch-alarm-map.models.lsn_loop_bypassable24_hour_intrusion_point_post import LSNLoopBypassable24HourIntrusionPointPost
from bosch-alarm-map.models.lsn_loop_bypassable_bolt_contact_point_post import LSNLoopBypassableBoltContactPointPost
from bosch-alarm-map.models.lsn_loop_bypassable_intrusion_point_post import LSNLoopBypassableIntrusionPointPost
from bosch-alarm-map.models.lsn_loop_device_post import LSNLoopDevicePost
from bosch-alarm-map.models.lsn_loop_failure_indication_property import LSNLoopFailureIndicationProperty
from bosch-alarm-map.models.lsn_loop_latching_bypassable_technical_point_post import LSNLoopLatchingBypassableTechnicalPointPost
from bosch-alarm-map.models.lsn_loop_non_bypassable24_hour_intrusion_point_post import LSNLoopNonBypassable24HourIntrusionPointPost
from bosch-alarm-map.models.lsn_loop_non_bypassable_bolt_contact_point_post import LSNLoopNonBypassableBoltContactPointPost
from bosch-alarm-map.models.lsn_loop_non_bypassable_intrusion_point_post import LSNLoopNonBypassableIntrusionPointPost
from bosch-alarm-map.models.lsn_loop_non_bypassable_technical_point_post import LSNLoopNonBypassableTechnicalPointPost
from bosch-alarm-map.models.lsn_loop_non_latching_bypassable_technical_point_post import LSNLoopNonLatchingBypassableTechnicalPointPost
from bosch-alarm-map.models.lsn_loop_non_silent_amok_point_post import LSNLoopNonSilentAmokPointPost
from bosch-alarm-map.models.lsn_loop_non_silent_holdup_point_post import LSNLoopNonSilentHoldupPointPost
from bosch-alarm-map.models.lsn_loop_retriggerable_bypassable_technical_point_post import LSNLoopRetriggerableBypassableTechnicalPointPost
from bosch-alarm-map.models.lsn_loop_silent_amok_point_post import LSNLoopSilentAmokPointPost
from bosch-alarm-map.models.lsn_loop_silent_duress_point_post import LSNLoopSilentDuressPointPost
from bosch-alarm-map.models.lsn_loop_silent_holdup_point_post import LSNLoopSilentHoldupPointPost
from bosch-alarm-map.models.lsnnd100_configuration import LSNND100Configuration
from bosch-alarm-map.models.lsnnd100_configuration_any_of import LSNND100ConfigurationAnyOf
from bosch-alarm-map.models.lsnnd200_configuration import LSNND200Configuration
from bosch-alarm-map.models.lsnnd200_configuration_any_of import LSNND200ConfigurationAnyOf
from bosch-alarm-map.models.lsnp_loop_point_device_post import LSNPLoopPointDevicePost
from bosch-alarm-map.models.lsnska100_configuration import LSNSKA100Configuration
from bosch-alarm-map.models.lsnska100_configuration_any_of import LSNSKA100ConfigurationAnyOf
from bosch-alarm-map.models.lsn_std_intr50_configuration import LSNStdIntr50Configuration
from bosch-alarm-map.models.lsn_std_intr50_configuration_any_of import LSNStdIntr50ConfigurationAnyOf
from bosch-alarm-map.models.lsn_std_intr51_configuration import LSNStdIntr51Configuration
from bosch-alarm-map.models.lsn_std_intr51_configuration_any_of import LSNStdIntr51ConfigurationAnyOf
from bosch-alarm-map.models.lsn_std_intr52_configuration import LSNStdIntr52Configuration
from bosch-alarm-map.models.lsn_std_intr52_configuration_any_of import LSNStdIntr52ConfigurationAnyOf
from bosch-alarm-map.models.lsn_std_intr53_configuration import LSNStdIntr53Configuration
from bosch-alarm-map.models.lsn_std_intr53_configuration_any_of import LSNStdIntr53ConfigurationAnyOf
from bosch-alarm-map.models.lsn_std_intr54_configuration import LSNStdIntr54Configuration
from bosch-alarm-map.models.lsn_std_intr54_configuration_any_of import LSNStdIntr54ConfigurationAnyOf
from bosch-alarm-map.models.lsn_std_intr55_configuration import LSNStdIntr55Configuration
from bosch-alarm-map.models.lsn_std_intr55_configuration_any_of import LSNStdIntr55ConfigurationAnyOf
from bosch-alarm-map.models.lsn_std_intr56_configuration import LSNStdIntr56Configuration
from bosch-alarm-map.models.lsn_std_intr56_configuration_any_of import LSNStdIntr56ConfigurationAnyOf
from bosch-alarm-map.models.lsnup370_t_configuration import LSNUP370TConfiguration
from bosch-alarm-map.models.lsnup370_t_configuration_any_of import LSNUP370TConfigurationAnyOf
from bosch-alarm-map.models.lsn_walktest_category_property import LSNWalktestCategoryProperty
from bosch-alarm-map.models.lsn_walktest_trigger_frequency_property import LSNWalktestTriggerFrequencyProperty
from bosch-alarm-map.models.lsn_gateway import LsnGateway
from bosch-alarm-map.models.lsn_gateway_list import LsnGatewayList
from bosch-alarm-map.models.lsnaux import Lsnaux
from bosch-alarm-map.models.lsnaux_list import LsnauxList
from bosch-alarm-map.models.lsnbus import Lsnbus
from bosch-alarm-map.models.lsnbus_list import LsnbusList
from bosch-alarm-map.models.main import Main
from bosch-alarm-map.models.main_list import MainList
from bosch-alarm-map.models.model_listcommand import ModelListcommand
from bosch-alarm-map.models.motion_detector_test_start_stop import MotionDetectorTestStartStop
from bosch-alarm-map.models.mumusergroup_mixarray import MumusergroupMixarray
from bosch-alarm-map.models.mumusergroup_mixarray_all_of_user_ids import MumusergroupMixarrayAllOfUserIds
from bosch-alarm-map.models.mumusergroup_sync_id import MumusergroupSyncID
from bosch-alarm-map.models.network_get import NetworkGet
from bosch-alarm-map.models.network_post import NetworkPost
from bosch-alarm-map.models.ntp_get import NtpGet
from bosch-alarm-map.models.ntp_get_custom import NtpGetCustom
from bosch-alarm-map.models.ntp_get_public import NtpGetPublic
from bosch-alarm-map.models.ntp_post import NtpPost
from bosch-alarm-map.models.output import Output
from bosch-alarm-map.models.output_list import OutputList
from bosch-alarm-map.models.panel import Panel
from bosch-alarm-map.models.panel_cpu_usage import PanelCpuUsage
from bosch-alarm-map.models.panel_cpu_usage_averages import PanelCpuUsageAverages
from bosch-alarm-map.models.panel_disk import PanelDisk
from bosch-alarm-map.models.panel_last_restart_reason import PanelLastRestartReason
from bosch-alarm-map.models.panel_meminfo import PanelMeminfo
from bosch-alarm-map.models.panel_oii_sessions import PanelOIISessions
from bosch-alarm-map.models.panel_panel import PanelPanel
from bosch-alarm-map.models.panel_post import PanelPost
from bosch-alarm-map.models.permission_model import PermissionModel
from bosch-alarm-map.models.permission_model_arm_category_permissions import PermissionModelArmCategoryPermissions
from bosch-alarm-map.models.permission_model_event_category_permissions import PermissionModelEventCategoryPermissions
from bosch-alarm-map.models.permission_model_id import PermissionModelID
from bosch-alarm-map.models.permission_model_list import PermissionModelList
from bosch-alarm-map.models.permission_model_list_all_of_list_inner import PermissionModelListAllOfListInner
from bosch-alarm-map.models.permission_model_maintenance_category_permissions import PermissionModelMaintenanceCategoryPermissions
from bosch-alarm-map.models.permission_model_operations_category_permissions import PermissionModelOperationsCategoryPermissions
from bosch-alarm-map.models.permission_model_remote_service_category_permissions import PermissionModelRemoteServiceCategoryPermissions
from bosch-alarm-map.models.permission_model_status_category_permissions import PermissionModelStatusCategoryPermissions
from bosch-alarm-map.models.permission_model_sync_id import PermissionModelSyncID
from bosch-alarm-map.models.permission_model_user_category_permissions import PermissionModelUserCategoryPermissions
from bosch-alarm-map.models.permission_modellist_post import PermissionModellistPost
from bosch-alarm-map.models.point import Point
from bosch-alarm-map.models.point_list import PointList
from bosch-alarm-map.models.post_accessmodel_request import PostAccessmodelRequest
from bosch-alarm-map.models.post_area_siid_request import PostAreaSIIDRequest
from bosch-alarm-map.models.post_areaandtimemodel_request import PostAreaandtimemodelRequest
from bosch-alarm-map.models.post_areas_request import PostAreasRequest
from bosch-alarm-map.models.post_batteries_request import PostBatteriesRequest
from bosch-alarm-map.models.post_day_model_request import PostDayModelRequest
from bosch-alarm-map.models.post_interprogram_siid_request import PostInterprogramSIIDRequest
from bosch-alarm-map.models.post_keypad_siid_request import PostKeypadSIIDRequest
from bosch-alarm-map.models.post_keypads_request import PostKeypadsRequest
from bosch-alarm-map.models.post_lsngw_config_request import PostLSNGWConfigRequest
from bosch-alarm-map.models.post_outputs_request import PostOutputsRequest
from bosch-alarm-map.models.post_permisionmodel_request import PostPermisionmodelRequest
from bosch-alarm-map.models.post_smartkeymodel_request import PostSmartkeymodelRequest
from bosch-alarm-map.models.post_specialdaymodel_request import PostSpecialdaymodelRequest
from bosch-alarm-map.models.post_timemodel_request import PostTimemodelRequest
from bosch-alarm-map.models.postlsn_gateway_siid_request import PostlsnGatewaySIIDRequest
from bosch-alarm-map.models.power_supply import PowerSupply
from bosch-alarm-map.models.power_supply_list import PowerSupplyList
from bosch-alarm-map.models.printer import Printer
from bosch-alarm-map.models.ps_can_op import PsCanOp
from bosch-alarm-map.models.ps_can_op_list import PsCanOpList
from bosch-alarm-map.models.sharedkey_get import SharedkeyGet
from bosch-alarm-map.models.sharedkey_post import SharedkeyPost
from bosch-alarm-map.models.smartkey import Smartkey
from bosch-alarm-map.models.smartkey_list import SmartkeyList
from bosch-alarm-map.models.smartkey_model import SmartkeyModel
from bosch-alarm-map.models.smartkey_model_id import SmartkeyModelID
from bosch-alarm-map.models.smartkey_model_list import SmartkeyModelList
from bosch-alarm-map.models.smartkey_model_list_all_of_list_inner import SmartkeyModelListAllOfListInner
from bosch-alarm-map.models.smartkey_model_list_post import SmartkeyModelListPost
from bosch-alarm-map.models.smartkey_model_sync_id import SmartkeyModelSyncID
from bosch-alarm-map.models.special_day_model import SpecialDayModel
from bosch-alarm-map.models.special_day_model_id import SpecialDayModelID
from bosch-alarm-map.models.special_day_model_list import SpecialDayModelList
from bosch-alarm-map.models.special_day_model_list_all_of_list_inner import SpecialDayModelListAllOfListInner
from bosch-alarm-map.models.special_day_model_sync_id import SpecialDayModelSyncID
from bosch-alarm-map.models.special_day_modellist_post import SpecialDayModellistPost
from bosch-alarm-map.models.statistics_common import StatisticsCommon
from bosch-alarm-map.models.statistics_db import StatisticsDb
from bosch-alarm-map.models.statistics_db_all_of_databases import StatisticsDbAllOfDatabases
from bosch-alarm-map.models.statistics_db_all_of_databases_path_to_database import StatisticsDbAllOfDatabasesPathToDatabase
from bosch-alarm-map.models.statistics_db_all_of_databases_path_to_database_counters import StatisticsDbAllOfDatabasesPathToDatabaseCounters
from bosch-alarm-map.models.statistics_db_all_of_databases_path_to_database_handles import StatisticsDbAllOfDatabasesPathToDatabaseHandles
from bosch-alarm-map.models.statistics_general import StatisticsGeneral
from bosch-alarm-map.models.statistics_get import StatisticsGet
from bosch-alarm-map.models.statistics_oii import StatisticsOii
from bosch-alarm-map.models.statistics_oii_all_of_clients_inner import StatisticsOiiAllOfClientsInner
from bosch-alarm-map.models.sub import Sub
from bosch-alarm-map.models.sub_list import SubList
from bosch-alarm-map.models.subscriptions_inner import SubscriptionsInner
from bosch-alarm-map.models.supervised_conns import SupervisedConns
from bosch-alarm-map.models.supervised_conns_list import SupervisedConnsList
from bosch-alarm-map.models.supervised_ipc import SupervisedIPC
from bosch-alarm-map.models.synchronization_ids import SynchronizationIDs
from bosch-alarm-map.models.syncstatus_allow_sending_user_dbif_armed import SyncstatusAllowSendingUserDBIfArmed
from bosch-alarm-map.models.syncstatus_keys_data import SyncstatusKeysData
from bosch-alarm-map.models.syncstatus_restart_counter import SyncstatusRestartCounter
from bosch-alarm-map.models.syncstatus_uptime import SyncstatusUptime
from bosch-alarm-map.models.time_in import TimeIn
from bosch-alarm-map.models.time_model import TimeModel
from bosch-alarm-map.models.time_model_id import TimeModelID
from bosch-alarm-map.models.time_model_list import TimeModelList
from bosch-alarm-map.models.time_model_list_all_of_list_inner import TimeModelListAllOfListInner
from bosch-alarm-map.models.time_model_period_in_days_inner import TimeModelPeriodInDaysInner
from bosch-alarm-map.models.time_model_sync_id import TimeModelSyncID
from bosch-alarm-map.models.time_modellist_post import TimeModellistPost
from bosch-alarm-map.models.time_out import TimeOut
from bosch-alarm-map.models.user import User
from bosch-alarm-map.models.user_activate import UserActivate
from bosch-alarm-map.models.user_basic_data import UserBasicData
from bosch-alarm-map.models.user_id import UserID
from bosch-alarm-map.models.user_model import UserModel
from bosch-alarm-map.models.user_model_list import UserModelList
from bosch-alarm-map.models.user_model_list_all_of_list_inner import UserModelListAllOfListInner
from bosch-alarm-map.models.user_model_post import UserModelPost
from bosch-alarm-map.models.user_model_sync_id import UserModelSyncID
from bosch-alarm-map.models.user_modellist_post import UserModellistPost
from bosch-alarm-map.models.users import Users
from bosch-alarm-map.models.walktest import Walktest
from bosch-alarm-map.models.walktest_list import WalktestList
from bosch-alarm-map.models.walktest_start import WalktestStart
from bosch-alarm-map.models.walktest_stop import WalktestStop
from bosch-alarm-map.models.walktest_wt_inner import WalktestWtInner

